introduced hack to fix ClassNotFoundException because org.slf4j.impl.StaticLoggerBinder included in gradle plugin but slf4j not, see https://intellij-support.jetbrains.com/hc/en-us/community/posts/208362685-java-lang-NoClassDefFoundError-since-2016-2-update